# Site settings
title: watr.li
subtitle: Building the Internet of Plants
email: xoxo@watr.li
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://watr.li" # the base hostname & protocol for your site
twitter_username: watr_li
github_username:  watr-li

# Build settings
markdown: kramdown
