inc:
  # Blog Information
  title:        "watr.li"
  subtitle:     "Building the Internet of Plants"
  cover_image:  blog-cover.jpg
  logo:         logo.png

  email: xoxo@watr.li

  # Company information
  company:      watr.li
  url:          "http://watr.li"
  github:       watr-li
  twitter:      watr_li
  gplus:        '101183822199340201470'
  about_link:   /about/

  # Product Information
  #product_link: http://incorporated.sendtoinc.com/
  #tagline:      "Get a modern blog for your company"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  watrli

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   false
    gplus:      false
    hn:         false


 # Analytics
  analytics:
    google: true # Add tracking code in _includes/_google-analytics.html


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss


authors:
  watrli:
    name: watr.li
    url: https://twitter.com/watr_li
    bio: Building the Internet of Plants
    image: logo-big.png
  lucas:
    name: Lucas Jenß
    url: https://twitter.com/fresskoma
    bio: Likes disrupting things.
    image: authors/lucas.jpg
  lotte:
    name: Lotte Steenbrink
    url: https://twitter.com/lotterleben
    bio: Because I can.
    image: authors/lotte.jpg
  martin:
    name: Martin Landsmann
    url: https://github.com/BytesGalore
    bio: For the plants.
    image: authors/martin.png
  peter:
    name: Peter Kietzmann
    url: https://github.com/PeterKietzmann
    bio: "<span style='font-size:13px'>Roses are red, violets are blue, Watr.li was watered and that's why it grew</span>"
    image: authors/peter.png

url:          "http://watr.li"
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil
emoji_dir:   images/emoji

# Show future posts
future:      false
show_drafts: false
limit_posts: 0
highlighter: pygments

relative_permalinks: true

permalink: :title.html
paginate_path: 'page:num'
paginate: 10

markdown:      Kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
