source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-assets'
gem 'maruku'
gem 'rake'
gem 'sass'
gem 'uglifier'
gem 'gemoji'
gem 'json'
gem 'bigdecimal'
gem 'webrick'
gem 'etc'
gem 'jekyll-paginate'